# Site settings
title: MarkBruns
email: MarkBruns@MarkBruns.com
description: An imperfect child of God ğŸŒŸ attempting to be an empathğŸ§ğŸ¾ who cannot possibly ever communicate how GRATEFUL I am to my Creator for every moment of my existence! Philippians 4:8-9
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
