# Site settings
title: MarkBruns
email: MarkBruns@MarkBruns.com
description: Child of God ğŸŒŸ EmpathğŸ§ğŸ¾ I cannot possibly ever communicate how GRATEFUL I am to my Creator for every moment of my existence! Philippians 4:8-9
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
